# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11hV9q2Cl0Q4tQsGLrVBx_YQKQmrvQvZ4
"""



import streamlit as st
import requests
from PIL import Image
from skimage.transform import resize
import tensorflow as tf

from numpy.lib.type_check import imag
def preprocess_image(image):
  image=resize(image,(64,64,3))
  image=tf.cast(image, tf.float32)/255.0
  return image

def classify_image(image):
    # Preprocess the image (resize, normalize, etc.)
    # Replace this with your image preprocessing code
    image = preprocess_image(image)
    model=pickle.load(open('/content/Deployment.ipynb', 'rb'))
    prediction=model.predict(image)
    return prediction

st.title("tumor classification")
st.subheader('check on your health')

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png"])
if uploaded_file is not None:
  image = Image.open(uploaded_file)

  st.image(image, caption='Uploaded Image', use_column_width=True)
  prediction = classify_image(image)
  st.write('Prediction:')
  st.write(prediction)
